// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublicHolidaysApi.Data;

#nullable disable

namespace PublicHolidaysApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PublicHolidaysApi.Models.Database.DayStatusEntity", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryCode", "Date");

                    b.ToTable("DayStatuses");
                });

            modelBuilder.Entity("PublicHolidaysApi.Models.Database.HolidayEntity", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("LocalizedNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("localized_names");

                    b.HasKey("CountryCode", "Date");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("PublicHolidaysApi.Models.Database.MaxConsecutiveFreeDaysEntity", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("MaxConsecutiveDays")
                        .HasColumnType("int");

                    b.HasKey("CountryCode", "Year");

                    b.ToTable("MaxConsecutiveFreeDays");
                });

            modelBuilder.Entity("PublicHolidaysApi.Models.Database.SupportedCountryEntity", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryCode");

                    b.ToTable("SupportedCountries");
                });
#pragma warning restore 612, 618
        }
    }
}
